{% set name = "napari-ndev" %}
{% set version = "0.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-ndev-{{ version }}.tar.gz
  sha256: ac0fb273bd25d84d328c7256fd6dd2c993cda90f49cfe855d3efbe5f1cbcbf03

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - aicsimageio
    - apoc-backend
    - dask-core
    - magicgui
    - napari
    - napari-workflows
    - numpy
    - pyclesperanto-prototype
    - python >=3.8
    - qtpy

test:
  imports:
    - napari_ndev
  commands:
    - pip list
    - pip check
  requires:
    - oclgrind
    - pip

about:
  home: https://pypi.org/project/napari-ndev
  summary: A collection of widgets to process images from start to finish--focused on neural development.
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/TimMonko/napari-ndev

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - TimMonko
