{% set name = "napari-ndev" %}
{% set version = "0.9.7" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 0a8e6bde3b2de64754bff03afdfa8c9981e0c68d6c51b532d68888c126b22294

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools-scm >=8
    - setuptools >=42

  run:
    - aicsimageio
    - apoc-backend
    - dask-core
    - magicgui
    - napari
    - napari-workflows
    - numpy
    - pyclesperanto-prototype
    - python >={{ python_min }}
    - qtpy

test:
  imports:
    - napari_ndev
  commands:
    - pip list
    - pip check
  requires:
    - oclgrind
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/napari-ndev
  summary: A collection of widgets to process images from start to finish--focused on neural development.
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/TimMonko/napari-ndev

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - TimMonko
