{% set name = "napari-ndev" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-ndev-{{ version }}.tar.gz
  sha256: 9763905d97a959271ce163076f1f70f2cfb413617bb141b0778df993ddbf02f5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - aicsimageio
    - apoc-backend
    - dask-core
    - magicgui
    - napari
    - napari-workflows
    - numpy
    - pyclesperanto-prototype
    - python >=3.8
    - qtpy

test:
  imports:
    - napari_ndev
  commands:
    - pip list
    - pip check
  requires:
    - oclgrind
    - pip

about:
  home: https://github.com/TimMonko/napari-ndev
  summary: A collection of plugin widgets by Tim Monko while in the Bastian lab -- focused on neural development.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - TimMonko
