{% set name = "napari-ndev" %}
{% set version = "0.9.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: ae90c71b3160e95b3ed2530b0c5cf3b59ac19eac039b53b2092392620af36454

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - aicsimageio
    - apoc-backend
    - dask-core
    - magicgui
    - napari
    - napari-workflows
    - numpy
    - pyclesperanto-prototype
    - python >=3.8
    - qtpy

test:
  imports:
    - napari_ndev
  commands:
    - pip list
    - pip check
  requires:
    - oclgrind
    - pip

about:
  home: https://pypi.org/project/napari-ndev
  summary: A collection of widgets to process images from start to finish--focused on neural development.
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/TimMonko/napari-ndev

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - TimMonko
